title: Github Pages Test
author: mobiusdt
email: mobiusdt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just trying out the Github Pages Learning Lab.

# social links
twitter_username: your-twitter-handle
github_username:  mobiusdt

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
